only_rules:
    - colon
    - fatal_error_message
    - implicitly_unwrapped_optional
    - legacy_cggeometry_functions
    - legacy_constant
    - legacy_constructor
    - legacy_nsgeometry_functions
    - operator_usage_whitespace
    - return_arrow_whitespace
    - trailing_newline
    - unused_optional_binding
    - vertical_whitespace
    - void_return
    - custom_rules
    - empty_string

included: # 린트 과정에 포함할 파일 경로. 이 항목이 존재하면 `--path`는 무시됨
    - SoSoHappy

excluded: # 린트 과정에서 무시할 파일 경로. `included`보다 우선순위 높음
    - Carthage
    - Pods
    - Source/ExcludedFolder
    - Source/ExcludedFile.swift
    - SoSoHappy/Application/AppDelegate.swift
    - SoSoHappy/Application/SceneDelegate.swift
